class CURL:
    main_site = 'https://stellarburgers.nomoreparties.site'
    register_user = f'{main_site}/api/auth/register'
    login_user = f'{main_site}/api/auth/login'
    logout_user = f'{main_site}/api/auth/logout'
    create_order = f'{main_site}/api/orders'
    ingredients = f'{main_site}/api/ingredients'
    delete_user = f'{main_site}/api/auth/user'
    data_user = f'{main_site}/api/auth/user'
    all_order = f'{main_site}/api/orders/all'